# Generated by Django 3.2.20 on 2023-07-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import signoffs.core.models.signets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signoffs_approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signoffs_signets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('final_signet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_signets.signet')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSignet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoff_id', models.CharField(max_length=100, validators=[signoffs.core.models.signets.validate_signoff_id], verbose_name='Signoff Type')),
                ('sigil', models.CharField(max_length=256, verbose_name='Signed By')),
                ('sigil_label', models.CharField(max_length=256, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='test_app.report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=128)),
                ('employee_signet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_signets.signet')),
            ],
        ),
        migrations.CreateModel(
            name='VacationSignet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoff_id', models.CharField(max_length=100, validators=[signoffs.core.models.signets.validate_signoff_id], verbose_name='Signoff Type')),
                ('sigil', models.CharField(max_length=256, verbose_name='Signed By')),
                ('sigil_label', models.CharField(max_length=256, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='test_app.vacation')),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevokeReportSignet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Revoked at')),
                ('signet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revoked', to='test_app.reportsignet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revoked by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionPermittingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('Initiated', 'Initiated'), ('Applied', 'Applied'), ('Permitted', 'Permitted'), ('Inspected', 'Inspected'), ('Approved', 'Approved')], default='Initiated', max_length=50)),
                ('apply_stamp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_approvals.stamp')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='test_app.building')),
                ('final_inspection_stamp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_approvals.stamp')),
                ('interim_inspection_stamp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_approvals.stamp')),
                ('permit_stamp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_approvals.stamp')),
            ],
        ),
    ]
