# Generated by Django 3.2.20 on 2024-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20240508_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.TextField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], default=('draft', 'Draft'), max_length=15),
        ),
    ]
